
    {RIL_UNSOL_STK_CALL_SETUP_STATUS, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_SETUP_RESULT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_SM_STATUS, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_SM_RESULT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_USSD_RESULT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_IMS_STATE_CHANGED, responseVoid, WAKE_PARTIAL}

