TOPDIR= ../../..
APPDIR= ./..

TARGET=rild-1  

CFLAGS= -I$(APPDIR)/include  -L$(LIBPATH)  -DRIL_SHLIB
LDFLAGS= -L$(LIBPATH) -lril_1  -ltrio-ril_1 -lrilutils_1  -lpthread -ldl -lrt -lstdc++


include $(TOPDIR)/Makefile.env
